modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="infinity_rpg"
version="1.0.0"
displayName=" infinity rpg"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="mimaf"

[[dependencies.infinity_rpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




